use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'SwiftyMDLib_Example' do
  pod 'SwiftyMDLib', :path => '../'
  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'SDWebImage'

  target 'SwiftyMDLib_Tests' do
    inherit! :search_paths

    
  end
end
